# Generated by Django 3.2.9 on 2021-11-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumerOrderSerializerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders',
            new_name='consumer',
        ),
    ]
