# Generated by Django 3.2.9 on 2021-11-21 15:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('consumerOrderSerializerApp', '0002_rename_orders_order_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
