# Generated by Django 3.2.9 on 2021-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvCourseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
